### ISSUE TITLE
[Suggestion] Load the map file in the local cache folder while the download process fails, instead of abort

### ISSUE THREAD

**Issue by TUsama** [Wynntils/Wynntils#1891] opened 2023-07-29 14:42 UTC
After the refactor of the [MapService.java](https://github.com/Wynntils/Artemis/blob/main/common/src/main/java/com/wynntils/services/map/MapService.java), the function [loadMaps](https://github.com/Wynntils/Artemis/blob/70c1146942ad4d5242e59f4ccc8b63bc08b4cde2/common/src/main/java/com/wynntils/services/map/MapService.java#L43) will abort the map load work if the client cannot link to some specified links, such as dataStaticAbilities, dataStaticMaps, and dataStaticUrls. this result in a black map occurs when you join the Wynncrafft, even if you have a brand new map cache in the cache folder.

I'll appreciate that if the dev can re-think this logic, or give an alternate way to load the map from the cache folder manually.

**Comment by kristofbolyai** [comment] 2023-07-30 08:35
Duplicate of https://github.com/Wynntils/Artemis/issues/1674

**Closed as completed by kristofbolyai** 2023-07-30 08:35 UTC

**Comment by magicus** [comment] 2023-07-30 08:57
But this report added some crucial new information. I'll move that over to #1674.
