### ISSUE TITLE
Notification strings are missing i18n

### ISSUE THREAD

**Issue by magicus** [Wynntils/Wynntils#752] opened 2022-11-29 09:43 UTC
When we converting chat messages to notifications, we have not used proper i18n for the new messages we sent to the NotificationManager.

**Comment by san7890** [comment] 2022-11-29 17:07
Dupe of https://github.com/Wynntils/Artemis/issues/626? Or do I misunderstand?

**Comment by kristofbolyai** [comment] 2022-11-29 17:07
It is!

**Closed as completed** 2022-11-29 17:08 UTC
